### ISSUE TITLE
Create clean/ca/orange_county_sheriff.py

### ISSUE THREAD

**Issue by jrynning** [biglocalnews/clean-scraper#17]
> Claimed by @jrynning

- agency slug (proposed): ca_orange_county_sheriff
- module: *clean/ca/orange_county.sheriff.py`
- url: https://www.ocsheriff.gov/about-ocsheriff/peace-officer-records-releases

### Tasks
- [x] Scrape and cache index pages
- [x] Scrape and cache detail pages
- [x] Download files from detail pages

### Scraping Plan
The Orange County Sheriff’s Department (OCSD) website should be pretty straightforward to scrape, since all the files are provided in zip files on one web page. 

So far, I am able to pull the HTML with the clean-scraper CLI, downloading it to the cache.

Next steps will be to get the metadata in JSON from HTML, get the actual files, and potentially to unzip and organize them. 

Converting the metadata to JSON should be fairly simple, since there is only one webpage, and I will compare it to the San Diego example so the format makes sense. 

To download the files, I think I should be able to use the requests library and URLs from the meta JSON. I will need to be sure to include code for throttling, and will also try to name and organize the downloads in a way that makes sense.

**Comment by zstumgoren** [comment]
Merged in #29
