### ISSUE TITLE
Create clean/ca/oakland_pd.py

### ISSUE THREAD

**Issue by xavierjmartinez** [biglocalnews/clean-scraper#22]
agency slug (proposed): ca_oakland_pd
url: [https://www.oaklandca.gov/resources/oakland-police-officers-and-related-sb-1421-16-incidents](https://www.oaklandca.gov/resources/oakland-police-officers-and-related-sb-1421-16-incidents
)
### Tasks
- [ ] Scrape and cache index pages
- [ ] Scrape and cache detail pages
- [ ] Download files from detail pages

### Scraping Plan
This uses next request
