### ISSUE TITLE
Create clean/ca/san_diego_pd.py

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/clean-scraper#4]
- **agency slug**: `ca_san_deigo_pd`
- **module**: `clean/ca/san_diego_pd.py`
- **urls**:
  - https://www.sandiego.gov/police/data-transparency/mandated-disclosures/sb16-sb1421-ab748

## Tasks

- [x] Scrape and cache index pages
- [x] Scrape and cache detail pages
- [x] Download files from detail pages

## Scraping Plan (site assessment)

Site contains a top-level index page, which links to downstream index pages (currently 9 pages total).

Each index page links out to child pages that contain videos and other files we're targeting.

Links to child/detail pages are embedded directly in the HTML of index pages, so we can use `requests` to download source code and gather .
